### ISSUE TITLE
Navigating back to transaction page leads to no data shown

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#100]
If I load a transaction page ([example](https://genesis.stackstoken.com/tx/3c2bed48c8367f3bf0bc398bd68e905edcca97e4800d75c96f06563779e3b42e)) then click on an address link then use the browser back button, the transaction page loads the second time without data.

## Before

<img width="851" alt="screen shot 2018-11-12 at 11 16 05" src="https://user-images.githubusercontent.com/28991/48341056-629b4700-e66c-11e8-806a-eebca681d304.png">

## After

<img width="853" alt="screen shot 2018-11-12 at 11 16 15" src="https://user-images.githubusercontent.com/28991/48341061-65963780-e66c-11e8-8e62-9742527fc28a.png">

**Comment by markmhx** [comment]
I've encountered a similar problem loading an address page ([example](https://genesis.stackstoken.com/address/stacks/SM3KJBA4RZ7Z20KD2HBXNSXVPCR1D3CRAV6Q05MKT)) and navigating back to it:

## Before

<img width="851" alt="screen shot 2018-11-12 at 11 27 00" src="https://user-images.githubusercontent.com/28991/48341665-e6096800-e66d-11e8-83db-8b1d100c07f2.png">


## After

<img width="852" alt="screen shot 2018-11-12 at 11 27 07" src="https://user-images.githubusercontent.com/28991/48341669-e86bc200-e66d-11e8-934c-c77634d35e26.png">

**Comment by timstackblock** [comment]
This is resolved, if I click the address link while on a transaction page then hit the back button to get back to the transaction page it takes me back and is no longer blank.
