### ISSUE TITLE
Lighten selection background color for search bar

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#101]
Right now the color is too dark to see easily.

<img width="390" alt="screen shot 2018-10-29 at 12 45 08" src="https://user-images.githubusercontent.com/28991/47647828-7a58d280-db78-11e8-8f07-908be1d41e60.png">

**Comment by timstackblock** [comment]
This is still the same color we have not lightened it yet

**Comment by hstove** [comment]
@timstackblock the fix applies a lighter color when you select text - it's definitely brighter, but I can always change it further. (cc @markmhx )

![screenshot](https://cl.ly/96e79462b3f0/Image%202019-06-04%20at%208.59.53%20PM.png)

**Comment by timstackblock** [comment]
Your correct this one is test passed sorry about that
