### ISSUE TITLE
Apply consistent casing strategy to headers

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#102]
<img width="937" alt="screen shot 2018-10-29 at 12 26 42" src="https://user-images.githubusercontent.com/28991/47646988-fd2c5e00-db75-11e8-9c48-2eec156d43f9.png">

**Comment by timstackblock** [comment]
This is still an issue everything says we till have STX listed on the unlocking schedule it should be changes to match everything else


![Screen Shot 2019-06-04 at 10.20.25 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/855c5d05-aac5-4d89-8456-b22e8ddc51fd)

![Screen Shot 2019-06-04 at 10.22.24 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6c72813f-f97d-4b04-be50-2b81ee838e86)

**Comment by timstackblock** [comment]
this is resolved
