### ISSUE TITLE
Ensure that order of recent names on homepage is always correct

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#104]
This was [originally posted by @hstove](https://github.com/blockstackpbc/stacks-explorer/issues/78)  in the now-deprecated repo.

**Comment by markmhx** [comment]
@hstove Is this ordering issue still a problem? And will it get resolved as part of the caching / API changes we're doing or is there a separate fix required?

**Comment by timstackblock** [comment]
This works well
