### ISSUE TITLE
Clicking the Block number link returns a blank page with no data

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#106]
1) Attempt to click on the block number link which appears clickable, you will notice it returns a blank page.

2 )Navigate to https://explorer.blockstack.org/tx/335b303a711c71130d10b440b0ac42100830e20407e875422f5832437650bb5c and select the block link 569896. 

3) We expect the link to return data and the Explorer should return the correct information about the Block

4) Explorer returns no information just a blank page

See video https://screencast-o-matic.com/watch/cqfhF2ZiKX |

**Comment by timstackblock** [comment]
@hstove @markmhx 

Many of the block links return undefined in the URL and cause an error, is this related to missing data or is this a real bug?

http://somup.com/cq1hVDnH8S

This is still an issue clicking the block number link returns undefined 

see screen shot below

![Screen Shot 2019-06-04 at 9.19.27 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/e434c39f-0eed-4591-9226-ee0b0d8fad04)

**Comment by timstackblock** [comment]
This work its just really slow

**Comment by timstackblock** [comment]
30 minute page loads http://somup.com/cq1h0anJTG, this doesn't seem to load.

**Comment by timstackblock** [comment]
Go to this page https://staging-explorer.blockstack.xyz/tx/6095b84ddc3a085ac0d8e129f0b22910a1fe1668cfc3e59b9cd1494ad9ae0afd and click the block number link 578874 you will get a really slow page load time and when it does load it brings back https://staging-explorer.blockstack.xyz/block/undefined and we hit an error page.

I am moving this back to In Progress.
 

Below is a video of how slow the page is loading.

http://somup.com/cq11DsnJHN

SCREENSHOTS BELOW
![Screen Shot 2019-06-06 at 12.53.31 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d8723d1e-916d-45f8-bfd7-113cff093f40)





![Screen Shot 2019-06-06 at 12.53.47 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/01c97fc8-ddc6-4944-8770-93e3f925bf66)

**Comment by hstove** [comment]
I'm unable to repro this - including on other TX pages. @markmhx are you seeing this?

**Comment by markmhx** [comment]
I'm unable to recreate as well – page loads fast when clicking the block link and it remains showing the right content.

**Comment by hstove** [comment]
The page will also load fast because it's likely cached right now, but you can also try different TX pages and search for different blocks. Even when the cache is cold, the page loads in a normal timeframe.

**Comment by timstackblock** [comment]
I just reproduced it check out the video and links below. Its definitely still an issue but its only affecting some blocks so I think it could be a data issue.

Video of issue
http://somup.com/cq11b8nJdS

Go to the link below 
https://staging-explorer.blockstack.xyz/address/stacks/SPJAEENMR9J30QSSQGPSQG8RKZNCB3D2E9WAKT53

![Screen Shot 2019-06-06 at 1.57.55 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/ee940999-72c4-41a6-8ad7-4aac5d27709a)


Then click into the transaction on the right and click the block number 572845

You will go to an empty block page, this time the URL doesn't state "undefined" it actually has the correct block number URL but the page does have errors when it is returned.

See the screenshots below.
![Screen Shot 2019-06-06 at 1.57.45 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d024eaad-9fee-4572-ab5f-00c06758c298)
