### ISSUE TITLE
Searching for Transaction number returns a blank page with no data

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#107]
1) Attempt to enter a valid transaction number and search by Transaction
 
2) Enter transaction number  335b303a711c71130d10b440b0ac42100830e20407e875422f5832437650bb5c in the search box and press enter 
 
3) We expect the Explorer to return information for the entered transaction number 
 
4) The explorer returns no information and a blank page

see video https://screencast-o-matic.com/watch/cqfhY5Zjni

**Comment by timstackblock** [comment]
This is still an issue  see screen shot below

![Screen Shot 2019-06-04 at 9.35.31 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/e9e20dee-b19b-4015-a479-3072894ba5b6)

**Comment by timstackblock** [comment]
@hstove @markmhx

**Comment by timstackblock** [comment]
this looks like its resolved

**Comment by hstove** [comment]
Looks resolved on my end, too - @timstackblock feel free to QA again or move to Done/Closed.
