### ISSUE TITLE
"view more blocks" button does not return more block data, it just disappears 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#108]
1)Attempt to select the option to View more Blocks 

2) Go to https://explorer.blockstack.org/blocks scroll to the bottom of the page and you will reach the end of the page and see a button to view more blocks. Click the button and more block data will appear at the bottom of the page 

3) Users expect that when we click the button more block data will appear at the bottom of the page. 

4) The button disappears but no more block data appears on the page

see video below https://screencast-o-matic.com/watch/cqfhYsZjnJ

**Comment by timstackblock** [comment]
I cannot go back to previous pages because the button to go back to a previous block does not work. 

This test is blocked @hstove @markmhx

**Comment by hstove** [comment]
The 'view more blocks' button goes away if there are no more blocks to show. This can often happen on the current day view, but if you go to a previous day, you should be able to 'view more blocks' and load in more.

**Comment by timstackblock** [comment]
this is resolved
