### ISSUE TITLE
Intermittent bug - View blocks from a past date Buttons stop working when scrolling back to last week 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#109]
Viewing blocks from a previous date seems to work sometimes. This is an intermittent bug that is most likely tied to rate limiting or data availability issues. We can use this bug as a place holder to retest once Blockstack Explorer reinforcements are done.

Go to https://explorer.blockstack.org/blocks click the date button in the top right corner it will show yesterdays date and today's date. Continue to click the button and go back 1 week. 

User clicks the date button going back one day each time they click it until they are one week from today's date. 

When viewing blocks from a previous day the user runs into an error page that states “something went wrong” and return no data. This is an intermittent issue it works some times and doesn't others.

**Comment by timstackblock** [comment]
User hits the PAGE NOT FOUND error when trying to view previous block data

Here is a video of the issue

http://somup.com/cq1hVfnH8u

@markmhx @hstove 

Here is a screenshot of the issue

![Screen Shot 2019-06-04 at 9.05.42 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/9385271e-567b-4978-b823-79f853ebe72a)

**Comment by hstove** [comment]
I'm not able to reproduce this - I've tried going back quite a bit and going back and forth between dates. If you can repro this, can you screenshot any console errors?

**Comment by timstackblock** [comment]
This is resolved I think when you fixed the transaction link this was affected it works for me consistently I no longer get an error. I will close this issue.
