### ISSUE TITLE
Ensure unlocking information isn't shown on STX addresses without vesting

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-explorer#116]
This address could be used for testing: SP3ZQCK09ETQD1XT0Q4JNJYBDQKPCF3J43V5R8NYV

**Comment by timstackblock** [comment]
SM3KJBA4RZ7Z20KD2HBXNSXVPCR1D3CRAV6Q05MKT this looks good

**Comment by timstackblock** [comment]
this is resolved
