### ISSUE TITLE
Clicking the transaction link in the top right corner returns an empty page

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#117]
Clicking the transaction link in the top right corner returns an empty page with no data

![Screen Shot 2019-06-04 at 9.58.59 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/3e77aa6e-3c4d-4f76-bf72-a98586be6dd6)

@hstove @markmhx new issue

**Comment by hstove** [comment]
Should be fixed now - devops fixed some invalid data in our tables.

**Comment by timstackblock** [comment]
This is resolved
