### ISSUE TITLE
FEES (BTC) is always 0 under details on the transaction page

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#118]
FEES (BTC) is always 0 under details on the transaction page, I haven't seen this field populated with anything other than 0 I think this is a bug.

![Screen Shot 2019-06-04 at 10.50.41 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/c6225012-e560-45ea-bc38-1f9b4dc23bc5)

@hstove @markmhx

**Comment by markmhx** [comment]
@timstackblock Do you have a transaction ID handy from one of your recent tests while QA'ing the browser that should have BTC fees associated with it?

**Comment by timstackblock** [comment]
TX# 338733b86596a78bdfb11c730eb8f427554fecf964ac0ad8236b1dc6b153dea0 

https://staging-explorer.blockstack.xyz/tx/338733b86596a78bdfb11c730eb8f427554fecf964ac0ad8236b1dc6b153dea0

I could be misinterpreting this but this was a STX transfer from a wallet and there were BTC fees


1P14e8ny8GeaxggYxku6VLiTEakeGaHo9R
0.000055
BTC
1LGPbjjn4WU9V9M8WBsNV86WvoqHc7vSoY
0.00089312
BTC

**Comment by hstove** [comment]
Fixed - some transactions do still have 0 fees, which are block reward transactions.

Here is one that does have fees: https://staging-explorer.blockstack.xyz/tx/23001785f23e351d9b24a37ab6b9be5777dacfee5fbe6f8e212b0ef2dff8ce09

**Comment by timstackblock** [comment]
still testing this but I think its fixed, what was the issue that caused the constant fee?

**Comment by timstackblock** [comment]
this is re
