### ISSUE TITLE
Improve display of zonefile

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#12]
Format and syntax highlight the zonefile.
It could also be interesting to parse and interpret the zonefile for visitors.

<img width="1222" alt="screen shot 2016-11-04 at 1 28 58 am" src="https://cloud.githubusercontent.com/assets/597182/19977589/08f33b14-a22f-11e6-91a4-bdb9a8a10baf.png">

**Comment by markmhx** [comment]
I'm closing this out since it doesn't appear we even display zone files now that we've redesigned the Explorer generally.
