### ISSUE TITLE
Fix timestamps on Homepage, transactions page

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-explorer#120]
Right now, due to the way the data is stored, I am creating estimates for timestamps based on the block it happened. This is too inaccurate (looking at prod data), and there is a way to get exact timestamps by loading separate data.

**Comment by timstackblock** [comment]
This works still doing a few test

**Comment by timstackblock** [comment]
Didn't mean to close, still testing

**Comment by timstackblock** [comment]
@hstove when trying to test this is it possible to get some data that is less than 1 day old so we can see if the hours are accurately displayed for newly created data.

Currently the data is 1 day old so all I can really test is that the name was created 1 day ago, we should probably pull  in some data to the staging environment that is a few hours old and see if the timestamp matches the creation time.

This is currently what I see on the homepage.

![Screen Shot 2019-06-06 at 1.11.22 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6eee92e9-a5f5-4b65-a54f-58b0aaf7d856)

**Comment by hstove** [comment]
The devops team is still working on keeping the data in real-time - we can ask @GInxh to manually update the data right now, but what they're working on will keep the data in sync automatically.

**Comment by timstackblock** [comment]
Ok sounds good once we get some fresh data that is less than a day old I can test to the hour to see how accurate the time is. Until then we can keep the ticket open in Ready for QA.

**Comment by timstackblock** [comment]
@hstove I think we have a little issue with the time stamp it seems to be off

Name 123abc123.id.blockstack
has a 10 June 19 13:06 (1:06pm EST) time stamp on the home page of https://staging-explorer.blockstack.xyz/

raw data has 
       "iat": "2019-06-10T11:56:19.548Z",
        "exp": "2020-06-10T11:56:19.548Z",


![Screen Shot 2019-06-11 at 12.04.01 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/95b5b2e4-9bf6-4aa8-897c-fa10a7318833)

**Comment by timstackblock** [comment]
I am going to keep this open so @hstove can investigate why the timestamp and the raw data time are not 9 and a half hours apart

**Comment by hstove** [comment]
I am deploying a change here to clearly display that these timestamps are in UTC - not EST.

A second point here is that the timestamp displayed is _not_ supposed to be the same as any timestamps in the profile.json object. The timestamps in the profile.json file are not related to the time that the name was registered.
