### ISSUE TITLE
From field is blank for several transaction page records in the new explorer

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#127]
From field is blank for several transaction page records in the new explorer

empty from field with a large amount of white space

https://staging-explorer.blockstack.xyz/tx/6ddef61ea4b641893a91f87a1f2780b271d874c3d56f278dc28e00d555c5ce79
![Screen Shot 2019-06-06 at 5.51.01 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/4370f845-cf80-40e3-8cfb-6b87388e1b83)

https://explorer.blockstack.org/tx/6ddef61ea4b641893a91f87a1f2780b271d874c3d56f278dc28e00d555c5ce79
![Screen Shot 2019-06-06 at 5.51.07 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/d73f5513-0f20-4463-92f8-dd496bf2191b)
@markmhx

**Comment by hstove** [comment]
I'd note that this is only for BTC TX pages - which we will be exposing less and less. If it's a STX transfer, the bug is not present. I am going to downgrade from p2 to p4

**Comment by jeffdomke** [comment]
Cool, will take out of milestone.
