### ISSUE TITLE
Staging app is broken on CI and is blocking test automation

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#147]
Please add :name and :id to DOM for search bar and top nav options

This is needed to move away from xpath element selections which is brittle and causes scripts to fail.

**Comment by timstackblock** [comment]
@hstove I though the reason the test were failing was because of the elements but its actually because of the staging app is broken.

**Comment by timstackblock** [comment]
Please see screen shots of the broken app on my test PR https://github.com/blockstack/blockstack-explorer/pull/149

**Comment by timstackblock** [comment]
https://user-images.githubusercontent.com/49165468/67224035-626c0580-f3fe-11e9-9493-ffe365673587.png

**Comment by hstove** [comment]
Fix pushed to #149
