### ISSUE TITLE
2019 offering locked tokens not showing up properly

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#150]
Tokens purchased in the 2019 offering aren’t displaying properly in the explorer:

Unlocked tokens display correctly but locked tokens show up as zero. I’ve seen this on one of my addresses and there have been reports of this in telegram as well.

Here’s a screenshot from telegram:

![D835BE1F-8319-41B5-86A5-917DA9F7EDFA](https://user-images.githubusercontent.com/597182/67068169-ca76dd80-f1ab-11e9-9f82-a9e626c0cc67.jpeg)

**Comment by sdyglg** [comment]
Me too

**Comment by meggert9** [comment]
same issue

**Comment by timstackblock** [comment]
Locked STX value is no longer 0
It is populating as expected

<img width="375" alt="Screen Shot 2019-10-18 at 2 29 43 PM" src="https://user-images.githubusercontent.com/49165468/67118835-c8b11800-f1b3-11e9-9eaa-b4d56967957b.png">

**Comment by meggert9** [comment]
Mine still shows 0 for Locked

**Comment by larrysalibra** [comment]
Looks fixed to me! Thanks for the quick turn around!

**Comment by meggert9** [comment]
Yeah looked good when checked a bit later. Thanks
