### ISSUE TITLE
Block 599758 shows a bitcoin reward of 1269213024 BTC

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#151]
In explorer go to https://explorer.blockstack.org/block/599758

Look in the left column for reward and you will see the block reward as REWARD
1269213024 BTC this is incorrect and around  $10,049,781,029,583 USD.

<img width="1078" alt="Screen Shot 2019-10-18 at 12 04 06 PM" src="https://user-images.githubusercontent.com/49165468/67109876-6cdc9400-f19f-11e9-8ae3-8a81162dd131.png">

@diwakergupta

**Comment by hstove** [comment]
We already removed a bunch of BTC-related info from this block, including this, per Muneeb's suggestions. Closing
