### ISSUE TITLE
Timestamp incorrect on several post hardfork transaction

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#152]
The time stamp is showing as a future date of Oct 26th for the unlocking transaction

https://explorer.blockstack.org/address/stacks/SPF2C2BVK4EYSW9HGD55XQ8AC0967HQA366VC6SP

<img width="1214" alt="Screen Shot 2019-10-18 at 12 29 15 PM" src="https://user-images.githubusercontent.com/49165468/67111501-08bbcf00-f1a3-11e9-9b2d-40312899af61.png">

**Comment by diwakergupta** [comment]
Per Hank: "all GENESIS_INIT events happen at block 373601, which did happen in 2015. its kind of how we always do these hard fork events, we timestamp them to the time when blockstack on BTC launched."

We should probably include some verbiage on the display page to clarify what the 2015 timestamp means.

@markmhx and @moxiegirl could you help with this?

**Comment by timstackblock** [comment]
@diwakergupta I updated the ticket but not the title there are transactions with a future date that are not GENISIS_INIT. These will need a fix from Hank

<img width="1213" alt="Screen Shot 2019-10-18 at 12 42 25 PM" src="https://user-images.githubusercontent.com/49165468/67112358-05294780-f1a5-11e9-9fc5-d20d7108005f.png">

**Comment by timstackblock** [comment]
Time stamp issue has been fixed I was able to pull up a few timestamps that were still incorrect but after a page refresh they updated as well. Hank will clear the cache in production so this does not happen.

<img width="1211" alt="Screen Shot 2019-10-18 at 1 39 49 PM" src="https://user-images.githubusercontent.com/49165468/67118323-a36fda00-f1b2-11e9-91a2-944627e4b202.png">
