### ISSUE TITLE
Transaction page coming up blank for the given transaction

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#153]
In explorer go to page :
https://explorer.blockstack.org/tx/30e6bc0011a881379231653491d27a32697f7c024c1f56fda75cd5f2f97f4612 

You will see the transaction page display with no data.

<img width="1220" alt="Screen Shot 2019-10-18 at 12 24 54 PM" src="https://user-images.githubusercontent.com/49165468/67111149-597ef800-f1a2-11e9-99e2-88650b5bb6a3.png">

**Comment by hstove** [comment]
@timstackblock , how are you getting to this page? That is not a valid BTC transaction.
