### ISSUE TITLE
Wording of "paid" vs "free" names

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-explorer#157]
The current division of "free" names vs "paid" names seems a bit artificial to me.

I understand the difference between subdomain and domains but most people visiting the explorer don't know this difference.

What do you think about:

(a) calling "free" names "usernames" -- that's what most people are registering them for.
(b) and "paid" names can be simply "domains".

**Comment by diwakergupta** [comment]
Looks like @hstove pushed a fix.
