### ISSUE TITLE
Improve search field

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#16]
Add search by:
*namespace ☑️
~~*name without the `.id~~ (shouldn't treat `.id` as privileged)
*partial name

**Comment by larrysalibra** [comment]
namespace search added in https://github.com/blockstack/blockstack-explorer/commit/1c024e71a373a335ffbafad5eba2e0cd5b649469

**Comment by markmhx** [comment]
I'm closing this since it appears to have been addressed
