### ISSUE TITLE
Proposal: Toggle BTC <-> STX on /address pages

### ISSUE THREAD

**Issue by lgalabru** [blockstack/blockstack-explorer#163]
I think it would be helpful to have a toggle STX / BTC when visiting a page showing an account (an STX link could be shown when visiting a BTC address, and vice versa).
For the users, it would help understanding the fact that for each STX address, you have a BTC address.
For the developers, it would be an easy way to do the back and forth between c32 and b58.

**Comment by hstove** [comment]
We used to show the BTC address on the STX address page, but the direction from leadership has been to remove as much BTC-related info as possible from STX pages. Sorry, going to close, although I certainly understand the reasoning here.

**Comment by moxiegirl** [comment]
@lgalabru When does a user interact with this BTC address, @lgalabru. I could potentially explain this in the documentation.
