### ISSUE TITLE
Only show message about unconfirmed TX's on TX 404 page

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-explorer#165]
We recently added a message to the error page, to indicate that we don't have info for unconfirmed TX's. It shows on all 404/error pages, but should only be on TX 404/error pages.

**Comment by timstackblock** [comment]
Resolved in #201 

<img width="1137" alt="Screen Shot 2020-01-29 at 12 48 07 PM" src="https://user-images.githubusercontent.com/49165468/73382494-9e342800-4295-11ea-98d1-475eca708756.png">
