### ISSUE TITLE
Total STX amount is incorrect - it is showing unlocked amount in the Total At This Address field

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-explorer#169]
![image](https://user-images.githubusercontent.com/52256509/67804228-5111a180-fa6d-11e9-805e-76b07a4563af.png)

https://explorer.blockstack.org/address/stacks/SP3XYDKJKRPESF0N83XN6EN3EC0FW5XGXSFD4A17F

Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by ryanarndtcm** [comment]
Seems to be resolved. This may have been a caching issue.

**Comment by hstove** [comment]
@timstackblock can you QA this? QA would basically be the same as the other ticket for 'locked' values being off.

**Comment by timstackblock** [comment]
This is resolved duplicate issue

<img width="995" alt="Screen Shot 2019-11-06 at 8 48 48 PM" src="https://user-images.githubusercontent.com/49165468/68353215-e13b9080-00d6-11ea-9ab9-b6797c710239.png">

<img width="1145" alt="Screen Shot 2019-11-06 at 8 48 34 PM" src="https://user-images.githubusercontent.com/49165468/68353216-e13b9080-00d6-11ea-9568-895d5e2eaa2a.png">
