### ISSUE TITLE
Show tooltip on labels in STX address card

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-explorer#180]

**Comment by jeffdomke** [comment]
"Stacks received from a hard fork with no unlocking schedule"

Might suggest: 

"Stacks received from a hard fork (unlocked)" 

Or just cut the unlock language, I think we have to assume Stacks are unlocked unless stated: 

"Stacks received from hard fork"

**Comment by moxiegirl** [comment]
@jeffdomke how does the hard fork figure in --- I mean, why do we have to provide that in this context?

**Comment by hstove** [comment]
The reason I added the "Token Grants" section is that these tokens were never "locked", so calling them "unlocked" didn't make sense to me.

**Comment by hstove** [comment]
@jeffdomke I've updated the copy of the 'token grants' tooltip to match what you suggested.
