### ISSUE TITLE
Two decimal places instead of three

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-explorer#182]
Looking at the latest staging built, I really like rounding the numbers after the decimal:

https://explorer.staging.blockstack.xyz/address/stacks/SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS

Can we do rounding down to two decimal places for all cases? Thanks!

**Comment by zone117x** [comment]
I can see how this rounding might look nice, but I'd argue that the explorer is a utility and that it should show STX values with full accuracy. 

For UI inspiration and examples:
* https://www.blockchain.com/btc/tx/a2c50cd346b0a814753ae07f6169925ff6eb230c36e82901f50873dc33c13a36
* https://moneroblocks.info/block/1961880
* https://etherscan.io/tx/0x28489733d28667a2e2556e6b6d47b062c071112c5c901ff7362b3dea3a9a5ce2

**Comment by diwakergupta** [comment]
I'm with @zone117x here, loss of precision could also come off as inaccurate or buggy for users / investors.

@jeffdomke care to weigh in?

**Comment by jeffdomke** [comment]
Yeah, tend to agree. Pretty normal for tokens to be moved around with extreme fractional units and rounding could lead to user error or misunderstanding.
