### ISSUE TITLE
NaN randomly appears in the place of some calculations 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/blockstack-explorer#186]
We have reported and attempted to fix this issue multiple times but it is still appears randomly. I am documenting this before the deploy to production so we can continue to debug the issue.

When we visit certain pages NaN randomly appears in the place of some calculations 

<img width="1288" alt="Screen Shot 2019-11-13 at 10 52 32 AM" src="https://user-images.githubusercontent.com/49165468/68780916-fb103280-0604-11ea-8233-3403431ba262.png">

**Comment by jeffdomke** [comment]
Assuming this is resolved on prod?
