### ISSUE TITLE
Urgent - CoinMarketCap Richlist with token addresses and supply.

### ISSUE THREAD

**Issue by blocks8** [blockstack/blockstack-explorer#189]
Request from CoinMarketCap: 
Web link to functional block explorer that contains a rich list or coin holder distribution table that we can use to verify the supply information.

**More context and examples:**

We kindly ask that you please provide our team with a link to functional block explorer that contains a rich list or coin holder distribution table that we can use to verify the supply information.

Please see the following examples of rich lists:
Chainlink (LINK): https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca#balances
Groestlecoin (GRS): https://chainz.cryptoid.info/grs/api.dws?q=rich
Dinerocoin (DIN): https://din.overemo.com/distribution
OmiseGO (OMG: https://etherscan.io/token/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07#balances

We can use such information to verify the supply details for STX.

**Comment by hstove** [comment]
My recommendation for building this:

On the API side, make a new aggregator for this info. This info can likely be pulled only from the `accounts` table, but with some grouping to only get the most recent info for an account (basically, the row with the highest block_id per address).

The distribution % could be setup to pull in the hard-coded value (from `aggregators/home-info`), which later would be updated to use whatever we build for https://github.com/blockstack/blockstack-explorer-api/issues/13.

Then, add an API controller method to expose this aggregator's data.

On the front-end, once we have the API built, we'll just create a new page to display this info. I can help with this, as we can likely re-use other components to display info in a UI consistent way.

Obviously, feel free to use your discretion on how you think is best to build this out - I'm just hoping to give some guidance given my context.
