### ISSUE TITLE
View more for transactions goes in a loop

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-explorer#190]
https://explorer.blockstack.org/transactions

If you go on "STX transactions" and "View more", the new transactions loaded are actually old transactions and it keeps loading these old transactions in a loop.

**Comment by timstackblock** [comment]
This issue still occurs, the "STX transaction" page still seems to show looping data.

STEPS TO REPRODUCE:

1. GO to the page and selected a transaction amount, I selected 13,176.005 STX
2. Select view more several times expanding the rows of data.
3. Search the page for the specific transaction amount with "command F"
4. The search box will return 3 instances of 13,176.005 STX on the page
5. Verify that the transaction is infact the same transaction

Memo
3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c
Block
614971
Timestamp
Tuesday, January 28th 2020, 7:21:14 pm
Sender
SM250WQMEKMF5PHJXM018MKGZB61ZP1HDA9T1X1W1
Recipient
SP3HMTYSSDR8PJX0QH8GJV1CY8EKRP34AZCGX1CAA

<img width="1141" alt="Screen Shot 2020-01-29 at 12 55 45 PM" src="https://user-images.githubusercontent.com/49165468/73383363-2d8e0b00-4297-11ea-9eb4-9d67ac2c78bb.png">

**Comment by diwakergupta** [comment]
This is fixed now, thanks @zone117x !
