### ISSUE TITLE
homepage not displaying stats correctly

### ISSUE THREAD

**Issue by wileyj** [blockstack/blockstack-explorer#193]
Occasionally, the homepage displays incorrect `Global Statistics` and the graph below is blank. 

![Screenshot 2019-12-12 09 53 21](https://user-images.githubusercontent.com/2847772/70724769-30be3f00-1cc9-11ea-946a-3076b64474e0.png)

**Comment by diwakergupta** [comment]
Just observed it as well:

<img width="468" alt="Screenshot 2019-12-13 13 17 11" src="https://user-images.githubusercontent.com/15990/70822214-08a70c80-1dab-11ea-8c76-f825dd196021.png">

**Comment by timstackblock** [comment]
<img width="493" alt="Screen Shot 2020-02-10 at 4 37 54 PM" src="https://user-images.githubusercontent.com/49165468/74192778-30d4af80-4c24-11ea-872b-27d2ca64a946.png">
