### ISSUE TITLE
Use Blockstack bootstrap theme

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#2]
@shea256 started some work on this in the bootstrap branch: https://github.com/blockstack/blockstack-explorer/commit/2d19eb92d1a558d18c8277456a8b1d854938f1cb

Insight-ui uses bootstrap 3.1.1 and [blockstack-bootstrap](https://github.com/blockstack/blockstack-bootstrap) is based on bootstrap 4 so will have to do some porting.

**Comment by shea256** [comment]
+1

**Comment by shea256** [comment]
👍

**Comment by guylepage3** [comment]
@larrysalibra we will be updating this theme. Also, we are actually using v4 for the current https://github.com/blockstack/blockstack-bootstrap.

**Comment by larrysalibra** [comment]
@guylepage3 cool. blockstack-explorer (based on insight-ui) unfortunately uses bootstrap 3.1.1 so we'll have to port it to v4. What's your timeframe for updating the theme?

**Comment by guylepage3** [comment]
Oh.. I see.. the current theme that you're using. Gotcha. I am wanting to address the theme in the coming week or two.

**Comment by larrysalibra** [comment]
Currently using a theme based on blockstack colors and typefaces.  No need to port this to the bootstrap v4 in the short term.

<img width="1223" alt="screen shot 2016-11-04 at 1 10 43 am" src="https://cloud.githubusercontent.com/assets/597182/19976693/d0a7ae1e-a22b-11e6-9fdb-824ecd2e2ee5.png">
