### ISSUE TITLE
Some date time displays missing 'UTC' suffix (incorrectly appear as local time)

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-explorer#205]
Example on the STX transaction page https://explorer.staging.blockstack.xyz/transactions

![image](https://user-images.githubusercontent.com/1447546/73388183-c6c11f80-429f-11ea-9898-9920cfafe2c9.png)

Note: all date times must be displayed as UTC rather than local time, since these pages often render on the server via next.js. Would be better to have local-aware formatting for these fields, as well as other locale-specific displays like number formatting -- opening in another issue.

**Comment by timstackblock** [comment]
resolved
