### ISSUE TITLE
Explorer/data issue

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack-explorer#225]
User images are not showing up on user profiles.
![image](https://user-images.githubusercontent.com/52256509/88846044-6f9ef780-d1bb-11ea-91e7-1ac9b9c9977c.png)

Explorer is also showing only 3 names, most recent is 2 days ago.
![image](https://user-images.githubusercontent.com/52256509/88845942-441c0d00-d1bb-11ea-962b-128272755810.png)

**Comment by dantrevino** [comment]
some profiles seem to work fine: https://explorer.blockstack.org/name/dantrevino.id, while others have are not displaying properties that once existed, for instance an image here: https://explorer.blockstack.org/name/layton.id

**Comment by ryanarndtcm** [comment]
Explorer is working again - but my photo is still missing.

**Comment by dantrevino** [comment]
Not an exhaustive search, but profiles with avatars not being displayed have extra `/` in them (ie `//avatar-0`):
profile ref: [layton.id](https://gaia.blockstack.org/hub/1J6LqoWPHfBx9sNrSBwVfGWphitD8Krftm/profile.json)
image url: https://gaia.blockstack.org/hub/1J6LqoWPHfBx9sNrSBwVfGWphitD8Krftm//avatar-0

profile ref: [ryanarndt.id.blockstack](https://gaia.blockstack.org/hub/15rAR88KJKa2JTSvUy9zVda4y3kCiTe3UQ/profile.json)
image url: https://gaia.blockstack.org/hub/15rAR88KJKa2JTSvUy9zVda4y3kCiTe3UQ//avatar-0

**Comment by bissisoft** [comment]
> Not an exhaustive search, but profiles with avatars not being displayed have extra `/` in them (ie `//avatar-0`):

@dantrevino they have always (at least over a year) had that extra slash. By the way Dan, out of thousands of blockstack users, you are the only one i have seen that has a working avatar image at the moment! What is your secret? :wink: Did you recently update your profile picture in the past week or what did you do? I cannot update mine at all after this bug.

**Comment by ryanarndtcm** [comment]
@markmhx any update on this? reports that is impacting multiple dapps.

**Comment by markmhx** [comment]
I suggest we close out this issue in favor of the one that @bissisoft filed in the Blockstack Browser repo (https://github.com/blockstack/blockstack-browser/issues/2061) since there doesn't appear to be any Explorer-specific problem here.

**Comment by markmhx** [comment]
@ryanarndtcm I believe we have a fix in place for this now per https://github.com/blockstackpbc/devops/issues/400#issuecomment-679133177

I'll close this out for now. Please reopen if you hear this reported again.
