### ISSUE TITLE
update ui framework to bootstrap v4.0.0-alpha.5

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-explorer#23]
Update blockstack-explorer ui framework from bootstrap v3 to latest release of twbs/boostrap to v4.0.0-alpha.5.

See https://github.com/twbs/bootstrap/releases/tag/v4.0.0-alpha.5

**Comment by larrysalibra** [comment]
We don't need to do this right now. We can consider using our design system after it is ready.
