### ISSUE TITLE
Reduce verbosity of logs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#28]
Earlier today, the explorer server ran out of disk space on its root partition. The process manager (pm2) logs command output which is good in case something dies. I set up a log rotator for pm2 which should minimize the problem is the future. I also moved the pm2 logs from the small 29gb root partition to the 1 TB /data partition.

It would also be great to reduce the amount of debug information that gets printed out by blockstack-server (we're running it with --foreground so that pm2)

@jcnelson, is there a command switch on the server to reduce verbosity?

**Comment by muneeb-ali** [comment]
@larrysalibra want to move this issue to blockstack-core? 

Maybe we can have 2-3 levels of verbosity.

**Comment by larrysalibra** [comment]
done -> https://github.com/blockstack/blockstack-core/issues/271

In the meantime, i've moved /var/log to /data/log (/data is a 1 TB partition) and symlinked /data/log to /var/log.
