### ISSUE TITLE
Add estimated expiration time of names.

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-explorer#29]
Would be great to see an estimated time for expiration on names as opposed to just block height.

**Comment by moxiegirl** [comment]
@jeffdomke @markmhx This has come up recently in the FAQ.  Seems like exploration should also appear in the explorer.

https://github.com/blockstack/blockstack-browser/issues/1079
https://github.com/blockstack/docs.blockstack/issues/143

name.id expires
name.id.blockstack never expires

Both end dates and perpetuity should be reflected when someone looks at their profile in the explorer and the browser.  Does not appear to be in the raw profile right now.

**Comment by markmhx** [comment]
@moxiegirl What do you think of this approach to showing the upcoming expiration date for a name and providing an option to "Renew Name" (which I envision sending the user to the following docs until we have a non-CLI way to renew)?

https://docs.blockstack.org/develop/clidocs#renew

<img width="413" alt="Screen Shot 2019-07-01 at 16 55 18" src="https://user-images.githubusercontent.com/28991/60446195-27607f00-9c21-11e9-9a8a-dadc54b76fc8.png">

**Comment by moxiegirl** [comment]
@markmhx Seems like we have a lot of redundant and conflicting headings here --- no where do we have a **Name** label except in the action which is confusing. So, maybe we can just use the name in the action if we know it already?

![image](https://user-images.githubusercontent.com/1347209/60537130-afe02d80-9cbc-11e9-8137-5ddd90cdebf0.png)

**Comment by markmhx** [comment]
We do have a redundancy tension between "ID" and "Name" in general (throughout the Explorer). Note how this page is accessed by navigating to "Names", we say "name" in the URL and operations say "NAME_*" (e.g. at https://explorer.blockstack.org/name/markmhendrickson.id).

I don't have a strong preference for choosing one term or the other for consistency, so I'm happy to use ID in the left-hand column here as your mockup depicts. But we may want to think through how to resolve this tension more thoroughly throughout our platform.

**Comment by RSky215** [comment]
I would personally love to see a non-CLI method for users to be notified as well as execute the renewal of an ID. Is this something being actively worked? If not, who is the best resource for us non-CLI folks to reach out to?

**Comment by markmhx** [comment]
@RSky215 Unfortunately, a non-CLI method to be notified or renew isn't being worked on actively at this time. And the CLI is the only method available to renew at the moment. 

Have you checked out the CLI documentation and concluded they're insufficient for your purposes?

https://docs.blockstack.org/develop/clidocs#renew

**Comment by RSky215** [comment]
I'm don't think this is a solution that will work for me. I have seen a thread on a website that was developed to to provide a UI for the layman like myself. (https://renewmyblockstackid.info)

Looks good - I'm just wary of entering any kind of seed or private key into a web browser. I assume the site is client side but also not aware of the risks well enough to feel entirely comfortable using it.

Any other thoughts on solutions?

**Comment by markmhx** [comment]
@RSky215 I think I spoke too soon since there is indeed an "easy to renew" feature being built for the Blockstack Browser at the moment: https://github.com/blockstack/blockstack-browser/pull/1938

Does that solution look good for your needs given the description there?
