### ISSUE TITLE
Explorer shouldn't accept uppercase names

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#30]
It incorrectly shows names with uppercase names (which are invalid) as available.

Example: https://explorer.blockstack.org/name/Guy.id

Should `404` or redirect to lowercase name.

**Comment by vsund** [comment]
Also happens with special chars in names: https://explorer.blockstack.org/name/nonexisting+.id

**Comment by larrysalibra** [comment]
This is fixed.
