### ISSUE TITLE
Story: Explorer update

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#42]
Users should be able to use an upgrade version of the explorer that: 
* uses the current core version
* properly displays verifications using the new verification system
* has updated endpoints (need to move these over into an issue from the paper document)

# Action items (in order of declining priority):

- Use Core API: https://github.com/blockstack/blockstack-explorer/issues/45
- Address page should list profile cards for owned names: https://github.com/blockstack/blockstack-explorer/issues/44
- Move to id.blockstack.org https://github.com/blockstack/blockstack-explorer/issues/49
- New endpoints https://github.com/blockstack/blockstack-explorer/issues/48
- Use search from core.blockstack.org: https://github.com/blockstack/blockstack-explorer/issues/43
- Show potentially valid blockstack transactions in current blocks https://github.com/blockstack/blockstack-explorer/issues/46

**Comment by shea256** [comment]
Also metatag previews for profiles without names.

**Comment by muneeb-ali** [comment]
Are we keeping both explorer.blockstack.org and id.blockstack.org? 

We can drop the last item if needed. It looks like all the other things are needed for the product when more users sign up.

**Comment by muneeb-ali** [comment]
This was marked as low-priority compared to browser work that @yknl is looking at.

**Comment by larrysalibra** [comment]
> Are we keeping both explorer.blockstack.org and id.blockstack.org?

I think we should add a permanent redirect of explorer.blockstack.org to id.blockstack.org. That's #49 

> This was marked as low-priority compared to browser work that @yknl is looking at.

Definitely. Browser is top priority!

**Comment by shea256** [comment]
+1 for dropping this:

> Show potentially valid blockstack transactions in current blocks #46

Also marked in the other thread to drop the redirect.

**Comment by shea256** [comment]
@yknl Checking in on the update on this.

**Comment by yknl** [comment]
@shea256 I've submitted the PR for this change here #53 
And currently working on setting up docker deployment for the explorer so we can save time in the future.

**Comment by larrysalibra** [comment]
Closing out this user story.
