### ISSUE TITLE
Use search from core.blockstack.org

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-explorer#43]
The search on explorer.blockstack is not showing some profiles (we've seen a few support tickets). 

I'd suggest using the search endpoint from https://core.blockstack.org instead. That's where the most recent version of search will live for now and we index pretty frequently there. 

Tagging @kantai who updated search there recently.

**Comment by larrysalibra** [comment]
@muneeb-ali when you say "Search isn't showing some profiles" do you mean that there's no results for a particular name (it doesn't appear to exist on the explorer), or that the name shows up, but the profile card doesn't render?

Explorer's "search" is very simple. There's no indexing. It is just:

If text has one period, assume it is a blockchain id and try to navigate to the page for that name.

If a name isn't showing up on the explorer, it point to a bigger/different problem.

- 

I think in the spirit of decentralization, and to make sure we're not all looking at one centralized view of the network, the explorer should run off of a separate blockstack core node that connects to a separate bitcoind node from our normal fleet (this is how it operates now). Ideally explorer search would function this way.

At the moment though, using search from core.blockstack.org seems like the pragmatic way to proceed.

**Comment by muneeb-ali** [comment]
No results for a particular name. 

Here is an example: 

jiceman exists:
https://explorer.blockstack.org/name/jiceman.id 

But doesn't show up in search on the explorer.

On the Core search it works:
https://core.blockstack.org/v1/search?query=jiceman

But also a search by name like this works:
https://core.blockstack.org/v1/search?query=eisenman

(Sometimes people do that instead of a username search) 

+1 to explorer having it's own Core node. I was suggesting core.blockstack.org as short-term fix. The main point I'm bringing up is that we should not spend time trying to improve/fix the search functionality on the explorer and should only work on search in one place i.e., Core.

**Comment by larrysalibra** [comment]
> The main point I'm bringing up is that we should not spend time trying to improve/fix the search functionality on the explorer and should only work on search in one place i.e., Core.

This! Yes x 10000

**Comment by yknl** [comment]
Moved lower priority after discussion with @shea256 @larrysalibra
