### ISSUE TITLE
New endpoints

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-explorer#48]
Root: id.blockstack.org

`/<name>.<tld>`
  Example: https://id.blockstack.org/larry.id

`/address/<address>`
  Example: https://id.blockstack.org/address/3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP

`/names`
  https://id.blockstack.org/names

**Comment by muneeb-ali** [comment]
Does the "." in /larry.id work in a browser?

**Comment by yknl** [comment]
Moved lower priority after discussion with @shea256 @larrysalibra

**Comment by markmhx** [comment]
@yknl Is this issue still relevant?

**Comment by yknl** [comment]
This is no longer relevant
