### ISSUE TITLE
Move to id.blockstack.org

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#49]
1. Ensure production server will work on id.blockstack.org (@larrysalibra) 
2. Move current `explorer.blockstack.org` records to `id.blockstack.org` (@shea256)
3. Add a permanent redirect to `explorer.blockstack.org` that so that old links don't break (@shea256)

**Comment by shea256** [comment]
Let's drop the redirect. Just explorer.blockstack.org.

**Comment by larrysalibra** [comment]
Not doing this.
