### ISSUE TITLE
Display profile metadata in address pages

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-explorer#55]
Display Twitter card metadata

**Comment by GinaAbrams** [comment]
@yknl how about the metadata updates? #54 and #47 as well? 🙈 😄

**Comment by yknl** [comment]
@GinaAbrams These issues haven't been completed yet 😅

**Comment by GinaAbrams** [comment]
NP, thanks for the update @yknl ! 👍

**Comment by yknl** [comment]
@shea256 Proposed metadata format which will show up on Twitter and Facebook cards 
The IP address will be replaced by explorer.blockstack.org in production

Facebook
![image](https://user-images.githubusercontent.com/29081231/32147614-a36aa34c-bcc0-11e7-92d8-582d86dc441b.png)

Without profile photo:
![image](https://user-images.githubusercontent.com/29081231/32147652-20fd2ece-bcc1-11e7-9d28-d140c4a1aa01.png)


Twitter
![image](https://user-images.githubusercontent.com/29081231/32147616-b0705ca8-bcc0-11e7-8734-f7dd19a6a9b9.png)

**Comment by shea256** [comment]
My first note is to look at how other companies like Facebook, Twitter, Medium, etc. are setting up their metadata.

<img width="556" alt="screen shot 2017-10-29 at 4 05 05 pm" src="https://user-images.githubusercontent.com/994646/32148140-bce00db4-bcc8-11e7-97fb-5efbe3f3773a.png">
<img width="541" alt="screen shot 2017-10-29 at 4 05 13 pm" src="https://user-images.githubusercontent.com/994646/32148141-bceaf54e-bcc8-11e7-8b25-ed6db03ce431.png">

**Comment by shea256** [comment]
So I'd say that "Blockstack" has to be in the title tag. Also the user's full name should come first.

Here are a few options for the title tag:

- Werner Vogels (werner.id) | Blockstack
- Werner Vogels (werner.id) on Blockstack
- Werner Vogels's Blockstack ID - werner.id
- werner.id: Werner Vogels on Blockstack

**Comment by shea256** [comment]
Can we also create a view that doesn't have /name/ in it?

It would look like:

https://explorer.blockstack.org/ryan.id

Instead of:

https://explorer.blockstack.org/name/ryan.id

There should be a simple way of doing this without introducing conflicts with other routes. Just look for a pattern like `/*.*` or something like that.

**Comment by shea256** [comment]
For the description, something should come before the bio. It could be something like:

---

<img src="https://user-images.githubusercontent.com/994646/32148456-b511e5e4-bccd-11e7-9d17-01b7e7f31dc3.jpg" width="100" />

**Werner Vogels's Blockstack ID - werner.id**

Werner Vogels (ryan.id) has registered an identity on Blockstack, a new internet for decentralized apps. CTO and VP at Amazon. PhD from Vrije Universiteit Amsterdam. Research at Cornell.

---

**Comment by yknl** [comment]
## Updated ##

Facebook: 
![image](https://user-images.githubusercontent.com/29081231/32148553-4a2052f0-bccf-11e7-98bb-10c5ace43262.png)

Twitter:
![image](https://user-images.githubusercontent.com/29081231/32148735-91bfc328-bcd1-11e7-91db-c3d72d496eeb.png)

## Fallback in case profile was not filled out ##
Facebook
![image](https://user-images.githubusercontent.com/29081231/32148889-16e43574-bcd3-11e7-95fd-c4adca9a7a87.png)


Twitter
![image](https://user-images.githubusercontent.com/29081231/32148864-bc1cdbb4-bcd2-11e7-8666-cf040ffa83a5.png)

**Comment by yknl** [comment]
> There should be a simple way of doing this without introducing conflicts with other routes. Just look for a pattern like /*.* or something like that.

We can setup a regex redirect (using nginx rewrite) from https://explorer.blockstack.org/ryan.id to https://explorer.blockstack.org/name/ryan.id

See: http://23.96.218.65/ryan.id

**Comment by shea256** [comment]
@yknl Ah I don't mean a redirect but an actual page destination. Adding a route.

**Comment by yknl** [comment]
Also a note about the implementation of this. Since scrapers don't pick up metadata generated by javascript (the explorer is an angular.js app); we're detecting the user agent and redirecting bots to a server-side rendered metadata only page. 

Example:
https://explorer.blockstack.org/name/ryan.id gets forwarded to https://explorer.blockstack.org/metadata/name/ryan.id

**Comment by shea256** [comment]
@yknl Oh interesting! We have a metadata problem currently for blockstack.org/blog. I wonder if we could do something similar there.

**Comment by yknl** [comment]
>I wonder if we could do something similar there.

We should be able to, I will investigate.

**Comment by shea256** [comment]
Note that we're dropping the new routes as regex-based routes are a challenge with Angular.

**Comment by yknl** [comment]
> Note that we're dropping the new routes as regex-based routes are a challenge with Angular.
I do have the nginx redirect solution ready though, if we want to use that.
