### ISSUE TITLE
Explorer metadata for address endpoints isn't getting picked up by Facebook

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-explorer#57]
<img width="1142" alt="screen shot 2017-10-31 at 2 34 30 pm" src="https://user-images.githubusercontent.com/994646/32242241-a43f9406-be48-11e7-9462-01058f800bd4.png">

**Comment by yknl** [comment]
@shea256 this issue may be caused by Facebook's caching strategy. If you click scrape again, it returns correct meta data. Facebook has probably scraped some of the URL's before we updated the explorer with metadata and is caching the old pages.

**Comment by shea256** [comment]
I tried scrape again but it didn't work for me. I'll try it again now.

**Comment by shea256** [comment]
OK it's working for me now.

**Comment by yknl** [comment]
It also doesn't display the image on the first scrape because the image loading is asynchronous.
