### ISSUE TITLE
Change copy on token banner

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-explorer#58]
The Call to Action is not very strong (just says "Introducing Blockstack Token: Learn more" and many people will be seeing people posting these links on twitter today and over the next week.

<img width="722" alt="screen shot 2017-11-01 at 4 30 43 pm" src="https://user-images.githubusercontent.com/5605552/32296434-a141c5dc-bf22-11e7-9ec1-a8924d251596.png">

****

Can we change this to get people registering?

<img width="742" alt="screen shot 2017-11-01 at 4 34 18 pm" src="https://user-images.githubusercontent.com/5605552/32296425-9cac6040-bf22-11e7-807e-68d5cbe1534e.png">

**Comment by pstan26** [comment]
Can be shorter, just needs to say "Blockstack Token Sale Registration Now Open: *Register Now*"

**Comment by yknl** [comment]
Updated and pushed live.

**Comment by pstan26** [comment]
BIG deal thanks Ken!!
