### ISSUE TITLE
Improve viral coefficient in explorer.blockstack.org with copy addition

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-explorer#63]
cc @shea256 @yknl @guylepage3 @larrysalibra 

Currently, when someone clicks on a social verification link like the one below...
![screen shot 2017-11-14 at 1 59 58 pm](https://user-images.githubusercontent.com/5605552/32798942-35503ba2-c944-11e7-8291-5101f13fc000.png)

...the person following them doesn't know what this means, even if they click the link...

![screen shot 2017-11-14 at 2 01 24 pm](https://user-images.githubusercontent.com/5605552/32799005-5c5be19c-c944-11e7-9ae5-1277bef66d49.png)

Could we add text like this on every explorer page (even for specific names): 

"**Blockstack is a new internet for decentralized apps, where users own their own data and identity.  People are signing up for Blockstack ID's, and socially verifying their profiles to claim their voucher for tokens on the new internet here https://blockstack.com/sale-registration**"

**Comment by pstan26** [comment]
cc @jperla ;-)

**Comment by shea256** [comment]
Thanks @jperla for surfacing this.

@yknl @larrysalibra Important to prioritize this as it would increase our viral coefficient.

Think we could get something out like this today?

Thinking it should be a card on the left or right with the explanation and a call to action to download the browser.

**Comment by yknl** [comment]
@shea256 shouldn't this info be on the address page? Since when the explorer link points to the address page.

**Comment by pstan26** [comment]
Nice KEN!

**Comment by pstan26** [comment]
@yknl can you make the link bold and blue instead of greyed out?

**Comment by yknl** [comment]
> @yknl can you make the link bold and blue instead of greyed out?

Done
