### ISSUE TITLE
Null btc transaction in account details

### ISSUE THREAD

**Issue by friedger** [blockstack/blockstack-explorer#71]
In https://genesis.stackstoken.com/address/14q6KTQgFwKmcVwmxo5yTsFsQQuDBsqAJF
the first transaction shows

> Send Null BTC

![bildschirmfoto von 2018-11-08 13-27-17](https://user-images.githubusercontent.com/1449049/48198742-172a2580-e35a-11e8-809b-b07730d90e00.png)

**Comment by aulneau** [comment]
Thanks for posting this @friedger! We will take a look! cc @hstove

**Comment by timstackblock** [comment]
resolved
