### ISSUE TITLE
Ensure content loads on homepage

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#73]
The "Last Names Registered" and "Recent Name Growth" sections load without any content fairly frequently, apparently due to data empty sets returned by the API (@hstove can describe best the underlying cause(s)).

This issue should resolve this problem either by ensuring that data always loads _or_ by replacing these sections with static components or other dynamic components that are more reliable.

Static components may actually be more useful anyway in guiding investors to check their allocations.

**Comment by markmhx** [comment]
Related: https://github.com/blockstack/blockstack-explorer/issues/81

**Comment by markmhx** [comment]
@hstove @kantai Assigning this to you both, please let me know if you need any more input on the goals here. But I believe the general API refactor we discussed last week is the core change here that will result in the homepage data loading consistently.

**Comment by hstove** [comment]
Homepage should be much improved, but note that timestamps are a little off, which is covered by #120

**Comment by timstackblock** [comment]
This is resolved
