### ISSUE TITLE
Clarify unlocking information on STX address page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#75]
The current STX address page's design includes a couple unclear data points in its left-hand column:

- Available balance
- Total received

These indicate the total STX _unlocked_ by address, not the total STX _owned_ by address. We should clarify that these indicate unlocked values and somehow clarify that "Total received" does _not_ include locked STX owned by the address (and perhaps explain how "receiving" works upon unlocking even though ownership occurs pre-receiving / unlocking).

We should also add a "Total owned balance" or something similar with the total (locked and unlocked) STX value so the user can compare in that area of the page.

<img width="397" alt="Screen Shot 2019-03-13 at 15 42 21" src="https://user-images.githubusercontent.com/28991/54287816-ac5a5680-45a6-11e9-9106-c9628331b34a.png">

Each transaction on the page also has a "Credit Value" data point that indicates the _cumulative_  STX unlocked upon that transaction, not the _incremental_ STX unlocked (which the name "credit value" might suggest). This "Credit Value" label should also be updated to indicate more clearly that it's cumulative (e.g. "Cumulative STX Unlocked"), and another value should perhaps be added as well for the incremental amount (e.g. "STX Unlocked"), placed above the cumulative one.

<img width="843" alt="Screen Shot 2019-03-13 at 15 43 04" src="https://user-images.githubusercontent.com/28991/54287835-b54b2800-45a6-11e9-99c5-2bef71076c26.png">

Furthermore, we may want to add an "STX UNLOCKED BY THIS ADDRESS" value up top next to the "STX OWNED BY THIS ADDRESS" value so the user can see these side-by-side.

<img width="993" alt="Screen Shot 2019-03-13 at 15 43 16" src="https://user-images.githubusercontent.com/28991/54287848-bc723600-45a6-11e9-8497-8b1dbdd0584a.png">

e.g. https://explorer.blockstack.org/address/stacks/SM3WAKDYSNKKMEB376GBAT6CYKS6ZWBKKS8B5AYC6

**Comment by markmhx** [comment]
@moxiegirl Mind providing your thoughts here on the best way to clarify this language?

**Comment by moxiegirl** [comment]
Lead with the total, and end with the amount available. It makes more sense instead of trying to create something that "adds" together like an equation. 

** Total address owns **
** Locked balance **
** Unlocked balance **

Roll over help for these may be useful.

Credit Value > **Unlocked balance**  -> Your explanation is a _bit_ confusing so we may need to ask about this but my reading of it is this should match what is currently the balance on the transaction.

**Transaction unlocked** for the new value.

> Furthermore, we may want to add an "STX UNLOCKED BY THIS ADDRESS" value up top next to the "STX OWNED BY THIS ADDRESS" value so the user can see these side-by-side.

This really belongs with the "details" on the left. Decide where you want this information and put it one place --- that's part of what is confusing.

**Comment by moxiegirl** [comment]
@markmhx @hstove Based on our conversation this week I would redo this dialog to something like this:

![image](https://user-images.githubusercontent.com/1347209/56832145-ff6b2e80-681f-11e9-9021-67c0612b42a1.png)

In the transaction history, I would allow the title of the various transaction types to be links that filter the transactions on the right.  Would require some additional interaction work to do this filter so maybe omit.

**Comment by markmhx** [comment]
@moxiegirl Thanks for this draft, I'll translate it into one in Figma.

And that's correct, theoretically not every address with have an unlocking schedule.

**Comment by moxiegirl** [comment]
@markmhx Thanks, if not every address the "unlock" info should be in the less prominent placement --- so in this layout, to the right. And rather than leave them out, I'd probably do a *N/A* there.

**Comment by markmhx** [comment]
@moxiegirl By "unlock info" here, you mean the "STX unlocking section" component in the right-hand column of your mockup? My sense is that any address without tokens waiting to unlock should simply omit that component.

Here are some label copy tweaks I'd recommend. What do you think?
 
![56833585-b4ebb100-6823-11e9-9137-a7ca5418dfd5](https://user-images.githubusercontent.com/28991/56932717-a1498000-6a99-11e9-9326-d45f4e5609f7.png)

**Comment by moxiegirl** [comment]
@markmhx 

* **Stacks (STX) Address Details** --- that first use clarifies/defines abbreviation


* it isn'tt necessary to preface every field with STX.  This is the Stacks blockchain explorer and the title is about STX.  Effectively this is like being in a bank account and having every field clarified that it contains US Dollars.

* Repeating the STX adjective weakens the scan on the detail fields

* Likewise, *CUMULATIVE ADDRESS ACTIVITY* is _under_ the *Stacks Address Details* so the word address is unneeded *CUMULATIVE TRANSACTION ACTIVITY* would be better --- it totals the values shown in the right pannel

**Comment by markmhx** [comment]
Come to think of it, wouldn’t readability be best – and values outputted in a most standard way – if we suffix all STX amounts online with the denomination instead of either a) omitting the denomination per label-value pair or b) including it in the label?

E.g. the first label-value pair could have label “Address Total” and value “321,050 STX”

This would seem consistent with how banks omit labeling accounts with denominations (e.g. they don’t say “Checking in USD”) while including the denomination in summaries and line items (e.g. “$81,492” not simply “81,492”).

**Comment by markmhx** [comment]
I’m mainly concerned with making the denomination in STX clear per value since we list lots of non-STX values throughout the explorer, including BTC ones in many places.

**Comment by moxiegirl** [comment]
@markmhx actually no, scanability is helped by differences in the first word. Moreover, all capital letters slow reading speed. Scanning is reading rapidly in order to find specific facts. Differences help and _shorter_ field names.

If your larger concern is reinforcing the STX I would suggest something else.  You should make this change:

Stacks (STX) Address Details --- that first use clarifies/defines abbreviation

Then you can after each amount do this:

`21,050 STX` it reinforces the concept of a currency without impacting the scan of the fields.

**Comment by markmhx** [comment]
I think we have the same solution in mind here: that we simply append "STX" to values (e.g. "21,050 STX") and leave it out of labels (e.g. "Total at this Address").

I don't think it's necessary to define the abbreviation "STX" for "Stacks" in this specific UI since we use "STX" throughout the Explorer (e.g. in transactions). If we learn that people get confused by what "STX" means, then we may want to define it _somewhere_. It just doesn't seem obvious to me that this is the most logical place to do so.

**Comment by moxiegirl** [comment]
This is not a preference issue on my part. Define an acronym as first use on a page is a standard editorial rule for acronyms.  Also, international language support, unlikely that non-native speaker will know phonetically that STX = Stacks. Heck, many US English speakers might also miss this. Finally, brand reinforcement just makes it a good sense thing to do.  

Adding the acronym in parens in the relevant heading clarifies this regardless of how someone lands on the page. 

It may make sense for me to take an editorial pass through all our pages, we lack consistency:


![image](https://user-images.githubusercontent.com/1347209/57242178-ba958380-6fe7-11e9-8c65-63922ab842bf.png)

**Comment by markmhx** [comment]
I’m happy to go with your recommendation here. Want to provide an updated mock-up with any changes resulting from this comment thread, adding the STX denominations at least?


Please do open other issues and include them in this epic if you want to apply more general consistency to Stacks vs STX guidance across the explorer. We may want to ask ourselves at some point whether we need to standardize that guidance in other materials as well.

**Comment by moxiegirl** [comment]
@markmhx This brings together everything I think.  Note the changes to the unlocking schedule. This rewording removes the future tense (unnecessary) and eliminates the footnote re the approximate date -- less ambiguous to a reader. Also, I've rearranged the second sentence to put the purpose to the fore as the second part of the sentence is reinforced by the hint text in the field.

![image](https://user-images.githubusercontent.com/1347209/57314390-669da400-70a6-11e9-83d7-c730167900f6.png)

**Comment by markmhx** [comment]
@moxiegirl looks good

@hstove any questions about the above design approach?

**Comment by hstove** [comment]
Nope, no questions, seems pretty actionable!

**Comment by timstackblock** [comment]
@markmhx @hstove 

I thought we wanted to remove the terms "credit value" it is still appearing when we click into the transaction

![Screen Shot 2019-06-04 at 10.37.02 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6db565ef-a041-4a00-832c-f8ad40c81dc8)

![Screen Shot 2019-06-04 at 10.40.12 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/5db6ea2e-ada3-4fd4-a02e-72797a1ac164)

**Comment by markmhx** [comment]
@moxiegirl Want to provide guidance on how to update the "Credit Value" label in transactions here to something more comprehensible and consistent with the other changes?

**Comment by hstove** [comment]
I can remove if you'd rather have that. `Credit value` and 'debit value` mean: "At this point in time, this address has sent/received this much STX total". The difference of those two is what your balance would be at that time.

**Comment by hstove** [comment]
I am going to close this out, as I created a new ticket in #122 that addresses the new concerns. The original ticket is all done.
