### ISSUE TITLE
Raise limit of transactions shown per pagination

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#76]
The current limit appears set to 5 transactions. We should lift this to 25 transactions to increase content visibility.

**Comment by hstove** [comment]
@markmhx I know we discussed which page this is on, but I forget now - can you be more specific about which page(s)?

**Comment by markmhx** [comment]
I believe we had name pages in mind (e.g. https://explorer.blockstack.org/name/muneeb.id), so if we lift or uncap the limit there, we should be good for this issue.

**Comment by timstackblock** [comment]
What is the limit can I get a parameter

**Comment by markmhx** [comment]
Let's just uncap entirely unless there's any objection. I doubt any names will have too many transactions for awhile for this to become a problem.

**Comment by hstove** [comment]
It's uncapped now. The limit used to be 5.

**Comment by timstackblock** [comment]
This works take a look at this address it has a large amount of transactions

https://staging-explorer.blockstack.xyz/address/stacks/SP3VJDN79TRQ3KX8PCV4J5ZSYX1JRTVA937SYKY1S
