### ISSUE TITLE
Ensure that transaction pages load

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#78]

**Comment by markmhx** [comment]
As with https://github.com/blockstack/blockstack-explorer/issues/73, it appears we need to refactor our API usage to make this fix.

**Comment by timstackblock** [comment]
This does not work when you search for the transaction, also the transaction link in the top right corner doesn't load. This is still an issue

**Comment by timstackblock** [comment]
Not sure if this is a bug it may be by design but it looks strange. Why is the from field empty with so much white space.


![Screen Shot 2019-06-05 at 1.31.35 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/804efeed-b36c-44cc-8cf9-f6a535c55051)

**Comment by timstackblock** [comment]
resolved
