### ISSUE TITLE
Ensure that searching addresses is fast

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#79]

**Comment by markmhx** [comment]
@kantai @hstove Who's best to take this one on? Is this related to our general API refactor work?

**Comment by hstove** [comment]
Probably me. But we may be limited by the speed of underlying API calls.

**Comment by timstackblock** [comment]
6 second page loads not sure if this is acceptable or not I will defer to @markmhx

**Comment by markmhx** [comment]
That's quite long...would prefer we get under 3 seconds (under 1 optimally). @hstove is this achievable?

**Comment by timstackblock** [comment]
Might actually be closer to ten seconds here is a video you can see how it loads

http://somup.com/cq1hbgnJD1

**Comment by timstackblock** [comment]
We still have some very slow 8 second page load times see the video below
http://somup.com/cq1XFPn7e7
