### ISSUE TITLE
Unregistered names appear as registered on explorer

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#80]
As of posting this issue, pinkpony.id isn't registered. 

<img width="726" alt="Screen Shot 2019-03-31 at 11 51 56 PM" src="https://user-images.githubusercontent.com/597182/55291323-fe590400-540f-11e9-9645-4b005b59eaf6.png">

The browser showed that it is available.

```
larry$ curl -I https://core.blockstack.org/v1/names/pinkpony.id
HTTP/2 404 
date: Sun, 31 Mar 2019 08:05:52 GMT
content-type: application/json
content-length: 28
set-cookie: __cfduid=d4f2564beb4c44f0b6d004f8e2248c51f1554019551; expires=Mon, 30-Mar-20 08:05:51 GMT; path=/; domain=.blockstack.org; HttpOnly
cache-control: public, max-age=300
access-control-allow-origin: *
access-control-allow-methods: GET
access-control-max-age: 21600
access-control-allow-headers: Origin
cf-cache-status: MISS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4c00d2145e448490-HKG
```

blockstack core shows that it is available.

<img width="848" alt="Screen Shot 2019-03-31 at 4 06 55 PM" src="https://user-images.githubusercontent.com/597182/55286508-12304600-53cf-11e9-8d55-d90d9cf74f6b.png">

Looking up the name on explorer appears as if it is registered

**Comment by GInxh** [comment]
Thanks Larry. Looking into this will get back to you.

**Comment by markmhx** [comment]
We currently show this page design as our generic 404 page for all unregistered names that the user attempts to view. To improve the UX here, we'd need to update the design.

e.g. https://explorer.blockstack.org/name/agwegaweawgawegawe

**Comment by markmhx** [comment]
Fix looks good to me

https://stacks-explorer.herokuapp.com/name/foooooobar

![Screen Shot 2019-05-03 at 17.35.29.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/f1b775a3-8c47-4092-aa75-60d9a5a8a297)
