### ISSUE TITLE
Homepage shows no names

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-explorer#81]
Names and the graph of name growth aren't appearing on the homepage

![1C273723-09E8-4F4D-B799-49F91627849B](https://user-images.githubusercontent.com/597182/55286799-00e93880-53d3-11e9-9cb4-ecbc521b49b6.png)

**Comment by GInxh** [comment]
Thanks Larry. As Hank mentioned, we get rate limited from an external resource and are lookng to move our API calls to this resource to bitcore, and host our own bitcore nodes. Looking to have it up asap. This is a priority but no gaurantees on time frame. As soon we can basically. Thanks.

**Comment by timstackblock** [comment]
This is resolved
