### ISSUE TITLE
Update stats labels to "Paid Names" and "Free Names"

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#89]
<img width="462" alt="screen shot 2019-01-15 at 13 34 47" src="https://user-images.githubusercontent.com/28991/51201561-621c6800-18ca-11e9-8076-57dd2f2ce381.png">

**Comment by moxiegirl** [comment]
As I understand it from @kantai for some namespaces the owner determines if there are fees if any. So, can we actually determine these two values? Like if they are outside of a namespace we actually created?

**Comment by moxiegirl** [comment]
@markmhx What is the status of what you are expecting here? No one answered my question (see above).

**Comment by markmhx** [comment]
I believe we discussed this subsequent to your question above and we determined it was possible to determine both values, and that @hstove just has to make the change in the UI.

**Comment by moxiegirl** [comment]
@markmhx Thanks, I forgot the discussion, next time I'll make sure I or someone else records a response on the ticket.
