### ISSUE TITLE
Remove hover background effect for transaction details that aren't links 

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer#93]
e.g.

<img width="561" alt="screen shot 2018-10-25 at 14 37 51" src="https://user-images.githubusercontent.com/28991/47500631-95b79b00-d863-11e8-9deb-145d6044f77a.png">

https://stacks-explorer-pr-17.herokuapp.com/tx/f9bb9d013f89cfec571b8530751e712ec500e8c7ef2e8d8f666b676c4f130a60

**Comment by timstackblock** [comment]
The hover link still seems to appear for transaction links that are not clickable ![Screen Shot 2019-05-03 at 12.10.50 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/339f4356-3cc6-4533-8b54-f41873857222)

**Comment by markmhx** [comment]
This issue refers to the background color of the cell itself upon cursor hover, not the color of the text itself regardless of cursor hover state.

The fix looks correct to me on staging here: https://stacks-explorer.herokuapp.com/tx/f9bb9d013f89cfec571b8530751e712ec500e8c7ef2e8d8f666b676c4f130a60

**Comment by timstackblock** [comment]
Thanks for the clarification
